.prettierignore
.stylelintignore
.eslintignore
.tscignore
.tsconfig.json
.stylelint.config.mjs
.eslint.config.mjs
.tsc.config.mjs
.prettier.config.mjs
.stylelint.config.mjs
.eslint.config.mjs
.tsc.config.mjs
.prettier.config.mjs
.agents/**/*.md
.agents/**/*.json
.agents/**/*.yaml
.agents/**/*.yml
.agents/**/*.xml
.agents/**/*.html
.agents/**/*.css
.agents/**/*.js
.agents/**/*.ts
.agents/**/*.tsx
.agents/**/*.jsx
.agents/**/*.json