import { CalendarIcon } from "@sanity/icons";
import { defineField, defineType } from "sanity";

const channelOptions = [
  { title: "Article", value: "article" },
  { title: "Neighborhood post", value: "neighborhood-post" },
  { title: "Google post", value: "google-post" },
  { title: "Email", value: "email" },
  { title: "Ad", value: "ad" },
  { title: "Postcard", value: "postcard" },
  { title: "Video", value: "video" },
] as const;

const statusOptions = [
  { title: "Idea", value: "idea" },
  { title: "Drafting", value: "drafting" },
  { title: "Scheduled", value: "scheduled" },
  { title: "Published", value: "published" },
] as const;

const generatedByOptions = [
  { title: "Manual", value: "manual" },
  { title: "Calendar agent", value: "calendar-agent" },
] as const;

/**
 * Private content-calendar planning entries. These are written as drafts by
 * `/api/content-calendar`, keeping internal marketing plans out of
 * public-read content.
 */
export const contentCalendarEntryType = defineType({
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      initialValue: "article",
      name: "channel",
      options: { layout: "radio", list: channelOptions },
      title: "Channel",
      type: "string",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      initialValue: "idea",
      name: "status",
      options: { layout: "radio", list: statusOptions },
      title: "Status",
      type: "string",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "scheduledFor",
      title: "Scheduled for",
      type: "date",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "targetKeyword",
      title: "Target keyword",
      type: "string",
    }),
    defineField({
      name: "brief",
      rows: 4,
      title: "Angle / brief",
      type: "text",
    }),
    defineField({
      name: "area",
      title: "Neighborhood / city focus",
      type: "string",
    }),
    defineField({
      description: "Desk lead that prompted this content, if any.",
      name: "sourceLead",
      title: "Source Desk lead",
      to: [{ type: "deskLead" }],
      type: "reference",
      weak: true,
    }),
    defineField({
      initialValue: "manual",
      name: "generatedBy",
      options: { layout: "radio", list: generatedByOptions },
      readOnly: true,
      title: "Generated by",
      type: "string",
    }),
    defineField({
      name: "createdAt",
      readOnly: true,
      title: "Created at",
      type: "datetime",
    }),
    defineField({
      name: "createdBy",
      readOnly: true,
      title: "Created by",
      type: "string",
    }),
  ],
  icon: CalendarIcon,
  name: "contentCalendarEntry",
  orderings: [
    {
      by: [{ direction: "asc", field: "scheduledFor" }],
      name: "scheduledForAsc",
      title: "Soonest scheduled",
    },
    {
      by: [{ direction: "asc", field: "status" }],
      name: "statusAsc",
      title: "Status",
    },
  ],
  preview: {
    prepare: ({ channel, scheduledFor, status, title }) => ({
      subtitle: [scheduledFor, channel, status].filter(Boolean).join(" · "),
      title: title || "Content calendar entry",
    }),
    select: {
      channel: "channel",
      scheduledFor: "scheduledFor",
      status: "status",
      title: "title",
    },
  },
  title: "Content calendar entry",
  type: "document",
});
