import { CheckmarkCircleIcon } from "@sanity/icons";
import { defineField, defineType } from "sanity";

const kindOptions = [
  { title: "Work task", value: "task" },
  { title: "Content calendar entry", value: "content" },
] as const;

const originOptions = [
  { title: "Seed (from the desk playbook)", value: "seed" },
  { title: "Generated (from the desk AI)", value: "generated" },
  { title: "Added by hand", value: "manual" },
] as const;

const statusOptions = [
  { title: "To do", value: "todo" },
  { title: "Done", value: "done" },
  { title: "Idea", value: "idea" },
  { title: "Scheduled", value: "scheduled" },
  { title: "Published", value: "published" },
] as const;

const buyerStageOptions = [
  { title: "Awareness", value: "awareness" },
  { title: "Consideration", value: "consideration" },
  { title: "Decision", value: "decision" },
  { title: "Retention", value: "retention" },
] as const;

/**
 * A single item on Tandra's Desk board — either a work task (with a To do / Done
 * status) or a content-calendar entry (with a pillar, buyer stage, and publish
 * date). Written by `/api/desk-board` and generated by `/api/desk-plan`, stored
 * as drafts so they stay out of public-read content.
 */
export const deskBoardItemType = defineType({
  fields: [
    defineField({
      initialValue: "task",
      name: "kind",
      options: { layout: "radio", list: kindOptions },
      title: "Kind",
      type: "string",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      validation: (Rule) => Rule.required().max(200),
    }),
    defineField({
      description:
        "Task: the outcome it produces. Content: the angle or promise of the piece.",
      name: "detail",
      rows: 3,
      title: "Detail",
      type: "text",
    }),
    defineField({
      description:
        "Task: where the work happens (direct mail, video, partner email). Content: searchable, shareable, or both.",
      name: "channel",
      title: "Channel or content type",
      type: "string",
    }),
    defineField({
      description: "Optional in-app path this item opens, e.g. /ads.",
      name: "href",
      title: "Deep link",
      type: "string",
    }),
    defineField({
      initialValue: "todo",
      name: "status",
      options: { layout: "radio", list: statusOptions },
      title: "Status",
      type: "string",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      initialValue: "manual",
      name: "origin",
      options: { layout: "radio", list: originOptions },
      title: "Origin",
      type: "string",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      description:
        "Stable key that links a status back to a hard-coded seed card on the Desk page.",
      name: "seedKey",
      readOnly: true,
      title: "Seed key",
      type: "string",
    }),
    defineField({
      description: "The topic cluster this content belongs to.",
      hidden: ({ parent }) => parent?.kind !== "content",
      name: "pillar",
      title: "Content pillar",
      type: "string",
    }),
    defineField({
      hidden: ({ parent }) => parent?.kind !== "content",
      name: "buyerStage",
      options: { layout: "radio", list: buyerStageOptions },
      title: "Buyer stage",
      type: "string",
    }),
    defineField({
      hidden: ({ parent }) => parent?.kind !== "content",
      name: "publishDate",
      title: "Publish date",
      type: "date",
    }),
    defineField({
      name: "createdBy",
      readOnly: true,
      title: "Created by",
      type: "string",
    }),
    defineField({
      name: "createdAt",
      readOnly: true,
      title: "Created at",
      type: "datetime",
    }),
    defineField({
      name: "completedAt",
      readOnly: true,
      title: "Completed at",
      type: "datetime",
    }),
  ],
  icon: CheckmarkCircleIcon,
  name: "deskBoardItem",
  preview: {
    prepare({ title, kind, status, publishDate }) {
      const kindLabel = kind === "content" ? "Content" : "Task";
      const suffix = publishDate ? ` · ${publishDate}` : "";
      return {
        subtitle: `${kindLabel} · ${status ?? "todo"}${suffix}`,
        title: title ?? "Untitled board item",
      };
    },
    select: {
      kind: "kind",
      publishDate: "publishDate",
      status: "status",
      title: "title",
    },
  },
  title: "Desk board item",
  type: "document",
});
