/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/roof.glb --types --output src/roof-model.tsx
*/

import { useGLTF } from "@react-three/drei";
import type { ThreeElements } from "@react-three/fiber";
import { staticFile } from "remotion";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Geom3D_4x10_Rafter: THREE.Mesh;
    Geom3D_4: THREE.Mesh;
    Geom3D_5: THREE.Mesh;
    Geom3D_2x6_Stud: THREE.Mesh;
    Geom3D_6: THREE.Mesh;
    Geom3D_Roof_Drip_Edge: THREE.Mesh;
    Geom3D_2x6_Stud_1: THREE.Mesh;
    Geom3D_2x6_Stud_2: THREE.Mesh;
    Geom3D_2x6_Stud_3: THREE.Mesh;
    Geom3D_7: THREE.Mesh;
    Geom3D_8: THREE.Mesh;
    Geom3D_9: THREE.Mesh;
    Geom3D_10: THREE.Mesh;
    Geom3D_2x_Wall_Plate: THREE.Mesh;
    Geom3D_: THREE.Mesh;
    Geom3D_11: THREE.Mesh;
    Geom3D_12: THREE.Mesh;
    Geom3D_13: THREE.Mesh;
    Geom3D_14: THREE.Mesh;
    Geom3D_15: THREE.Mesh;
    Geom3D_16: THREE.Mesh;
    Geom3D_17: THREE.Mesh;
    Geom3D_18: THREE.Mesh;
    Geom3D_19: THREE.Mesh;
    Geom3D_20: THREE.Mesh;
    Geom3D_21: THREE.Mesh;
    Geom3D_22: THREE.Mesh;
    Geom3D_23: THREE.Mesh;
    Geom3D_24: THREE.Mesh;
    Geom3D_25: THREE.Mesh;
    Geom3D_26: THREE.Mesh;
    Geom3D_27: THREE.Mesh;
    Geom3D_28: THREE.Mesh;
    Geom3D_29: THREE.Mesh;
    Geom3D_30: THREE.Mesh;
    Geom3D_31: THREE.Mesh;
    Geom3D_32: THREE.Mesh;
    Geom3D_33: THREE.Mesh;
    Geom3D_34: THREE.Mesh;
    Geom3D_35: THREE.Mesh;
    Geom3D_36: THREE.Mesh;
    Geom3D_37: THREE.Mesh;
    Geom3D_38: THREE.Mesh;
    Geom3D_39: THREE.Mesh;
    Geom3D__1: THREE.Mesh;
    Geom3D_40: THREE.Mesh;
    Geom3D_41: THREE.Mesh;
    Geom3D_42: THREE.Mesh;
    Geom3D_43: THREE.Mesh;
    Geom3D_44: THREE.Mesh;
    Geom3D_45: THREE.Mesh;
    Geom3D_46: THREE.Mesh;
    Geom3D_47: THREE.Mesh;
    Geom3D_48: THREE.Mesh;
    Geom3D_49: THREE.Mesh;
    Geom3D_50: THREE.Mesh;
    Geom3D_51: THREE.Mesh;
    Geom3D_52: THREE.Mesh;
    Geom3D_53: THREE.Mesh;
    Geom3D_54: THREE.Mesh;
    Geom3D_55: THREE.Mesh;
    Geom3D_56: THREE.Mesh;
    Geom3D_57: THREE.Mesh;
    Geom3D_58: THREE.Mesh;
    Geom3D_59: THREE.Mesh;
    Geom3D_60: THREE.Mesh;
    Geom3D_61: THREE.Mesh;
    Geom3D_62: THREE.Mesh;
    Geom3D_63: THREE.Mesh;
    Geom3D_64: THREE.Mesh;
    Geom3D_65: THREE.Mesh;
    Geom3D_66: THREE.Mesh;
    Geom3D_67: THREE.Mesh;
    Geom3D_68: THREE.Mesh;
    Geom3D_69: THREE.Mesh;
    Geom3D_Roof_Drip_Edge_1: THREE.Mesh;
    Geom3D_4x10_Rafter_1: THREE.Mesh;
    Geom3D_70: THREE.Mesh;
    Geom3D_2x6_Stud_4: THREE.Mesh;
    Geom3D_4x10_Rafter_2: THREE.Mesh;
    Geom3D_71: THREE.Mesh;
    Geom3D_72: THREE.Mesh;
    Geom3D_2x_Wall_Plate_1: THREE.Mesh;
    Geom3D_73: THREE.Mesh;
    Geom3D_74: THREE.Mesh;
    Geom3D__2: THREE.Mesh;
    Geom3D_75: THREE.Mesh;
    Geom3D__3: THREE.Mesh;
    Geom3D_76: THREE.Mesh;
    Geom3D__4: THREE.Mesh;
    Geom3D__5: THREE.Mesh;
    Geom3D__6: THREE.Mesh;
    Geom3D_77: THREE.Mesh;
    Geom3D__7: THREE.Mesh;
    Geom3D_78: THREE.Mesh;
    Geom3D_Difference: THREE.Mesh;
    Geom3D_79: THREE.Mesh;
    Geom3D_80: THREE.Mesh;
    Geom3D_81: THREE.Mesh;
    Geom3D_82: THREE.Mesh;
    Geom3D_83: THREE.Mesh;
    Geom3D__8: THREE.Mesh;
    Geom3D_84: THREE.Mesh;
    Geom3D_85: THREE.Mesh;
    Geom3D_86: THREE.Mesh;
    Geom3D_87: THREE.Mesh;
    Geom3D_88: THREE.Mesh;
    Geom3D_89: THREE.Mesh;
    Geom3D_90: THREE.Mesh;
    Geom3D_91: THREE.Mesh;
    Geom3D_92: THREE.Mesh;
    Geom3D_93: THREE.Mesh;
    Geom3D_94: THREE.Mesh;
    Geom3D_95: THREE.Mesh;
    Geom3D_96: THREE.Mesh;
    Geom3D__9: THREE.Mesh;
    Geom3D: THREE.Mesh;
    Geom3D_1: THREE.Mesh;
    Geom3D_2: THREE.Mesh;
    Geom3D_3: THREE.Mesh;
  };
  materials: {
    Plywood_08_1K: THREE.MeshStandardMaterial;
    "Maple Solid": THREE.MeshStandardMaterial;
    Roofing_01_1K: THREE.MeshStandardMaterial;
    "[Metal_Aluminum_Anodized]1": THREE.MeshStandardMaterial;
    Default: THREE.MeshStandardMaterial;
    "<LC>Roof Vent_Material1": THREE.MeshStandardMaterial;
    "[Color M09]": THREE.MeshStandardMaterial;
    "western-red-cedar": THREE.MeshStandardMaterial;
    "[Wood OSB]": THREE.MeshStandardMaterial;
    Metal_06_1K: THREE.MeshStandardMaterial;
    "<auto>19": THREE.MeshStandardMaterial;
    D01_Frost_White: THREE.MeshStandardMaterial;
    "131_gray slate roofing texture-seamless": THREE.MeshStandardMaterial;
    "Carpet_01_1K copy": THREE.MeshStandardMaterial;
  };
  animations: THREE.AnimationClip[];
};

export function Model(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(
    staticFile("roof.glb")
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0.05}>
          <group position={[106.692, 100.375, 110.932]}>
            <group
              position={[1.289, 40.053, 3.875]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Geom3D_4x10_Rafter.geometry}
                material={materials.Plywood_08_1K}
              />
              <mesh
                geometry={nodes.Geom3D_4.geometry}
                material={materials["Maple Solid"]}
              />
            </group>
            <group
              position={[94.443, 76.091, 46.575]}
              rotation={[0.002, -0.324, 3.14]}
              scale={[1.036, 1, 0.84]}
            >
              <group position={[0, -0.188, -1.533]}>
                <mesh
                  geometry={nodes.Geom3D_6.geometry}
                  material={materials["[Metal_Aluminum_Anodized]1"]}
                />
                <mesh
                  geometry={nodes.Geom3D_Roof_Drip_Edge.geometry}
                  material={materials.Default}
                />
              </group>
            </group>
            <group
              position={[81.715, 11.574, 42.623]}
              rotation={[0, 0, -Math.PI / 2]}
            >
              <mesh
                geometry={nodes.Geom3D_7.geometry}
                material={materials["<LC>Roof Vent_Material1"]}
              />
              <mesh
                geometry={nodes.Geom3D_8.geometry}
                material={materials["<LC>Roof Vent_Material1"]}
              />
              <mesh
                geometry={nodes.Geom3D_9.geometry}
                material={materials["<LC>Roof Vent_Material1"]}
              />
            </group>
            <group position={[50.664, 4.553, 19.167]}>
              <mesh
                geometry={nodes.Geom3D_10.geometry}
                material={materials.Plywood_08_1K}
              />
              <mesh
                geometry={nodes.Geom3D_2x_Wall_Plate.geometry}
                material={materials.Plywood_08_1K}
              />
            </group>
            <group position={[92.915, 0.921, 47.044]} scale={0.912}>
              <group
                position={[9.202, 83, 0.16]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[0.365, 0.64, 0.64]}
              >
                <group
                  position={[225.123, 0.196, -0.25]}
                  rotation={[0, 0, Math.PI]}
                  scale={[1.01, 1, 1]}
                >
                  <group position={[0, 0, 0.222]}>
                    <mesh
                      geometry={nodes.Geom3D_11.geometry}
                      material={materials["[Color M09]"]}
                      position={[15.876, -0.139, -6.233]}
                      rotation={[0, -0.03, 0]}
                      scale={[1.12, 1, 1]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_12.geometry}
                      material={materials["[Color M09]"]}
                      position={[29.349, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_13.geometry}
                      material={materials["[Color M09]"]}
                      position={[-167.094, -0.139, -5.227]}
                      rotation={[0, -0.03, 0]}
                      scale={[0.931, 1, 1]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_14.geometry}
                      material={materials["[Color M09]"]}
                      position={[-48.026, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_15.geometry}
                      material={materials["[Color M09]"]}
                      position={[-63.526, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_16.geometry}
                      material={materials["[Color M09]"]}
                      position={[-55.776, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_17.geometry}
                      material={materials["[Color M09]"]}
                      position={[-17.026, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_18.geometry}
                      material={materials["[Color M09]"]}
                      position={[-32.526, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_19.geometry}
                      material={materials["[Color M09]"]}
                      position={[6.099, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_20.geometry}
                      material={materials["[Color M09]"]}
                      position={[21.599, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_21.geometry}
                      material={materials["[Color M09]"]}
                      position={[13.849, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_22.geometry}
                      material={materials["[Color M09]"]}
                      position={[-172.026, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_23.geometry}
                      material={materials["[Color M09]"]}
                      position={[-9.276, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_24.geometry}
                      material={materials["[Color M09]"]}
                      position={[-1.526, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_25.geometry}
                      material={materials["[Color M09]"]}
                      position={[-156.526, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_26.geometry}
                      material={materials["[Color M09]"]}
                      position={[-24.776, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_27.geometry}
                      material={materials["[Color M09]"]}
                      position={[-141.026, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_28.geometry}
                      material={materials["[Color M09]"]}
                      position={[-86.776, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_29.geometry}
                      material={materials["[Color M09]"]}
                      position={[-133.276, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_30.geometry}
                      material={materials["[Color M09]"]}
                      position={[-79.026, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_31.geometry}
                      material={materials["[Color M09]"]}
                      position={[-164.276, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_32.geometry}
                      material={materials["[Color M09]"]}
                      position={[-117.776, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_33.geometry}
                      material={materials["[Color M09]"]}
                      position={[-40.276, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_34.geometry}
                      material={materials["[Color M09]"]}
                      position={[-125.526, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_35.geometry}
                      material={materials["[Color M09]"]}
                      position={[-110.026, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_36.geometry}
                      material={materials["[Color M09]"]}
                      position={[-102.276, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_37.geometry}
                      material={materials["[Color M09]"]}
                      position={[-94.526, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_38.geometry}
                      material={materials["[Color M09]"]}
                      position={[-148.776, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_39.geometry}
                      material={materials["[Color M09]"]}
                      position={[-71.276, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                  </group>
                  <mesh
                    geometry={nodes.Geom3D_.geometry}
                    material={materials["[Color M09]"]}
                    position={[220.874, Math.PI, 0]}
                    rotation={[0, 0, 0.007]}
                    scale={[1.21, 1, 1]}
                  />
                </group>
              </group>
              <group
                position={[8.14, 83, 0.16]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[0.365, 0.64, 0.64]}
              >
                <group
                  position={[225.123, 0.196, -0.25]}
                  rotation={[0, 0, Math.PI]}
                  scale={[1.01, 1, 1]}
                >
                  <group position={[0, 0, 0.222]}>
                    <mesh
                      geometry={nodes.Geom3D_40.geometry}
                      material={materials["[Color M09]"]}
                      position={[15.876, -0.139, -6.233]}
                      rotation={[0, -0.03, 0]}
                      scale={[1.12, 1, 1]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_41.geometry}
                      material={materials["[Color M09]"]}
                      position={[29.349, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_42.geometry}
                      material={materials["[Color M09]"]}
                      position={[-167.094, -0.139, -5.227]}
                      rotation={[0, -0.03, 0]}
                      scale={[0.931, 1, 1]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_43.geometry}
                      material={materials["[Color M09]"]}
                      position={[-48.026, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_44.geometry}
                      material={materials["[Color M09]"]}
                      position={[-63.526, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_45.geometry}
                      material={materials["[Color M09]"]}
                      position={[-55.776, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_46.geometry}
                      material={materials["[Color M09]"]}
                      position={[-17.026, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_47.geometry}
                      material={materials["[Color M09]"]}
                      position={[-32.526, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_48.geometry}
                      material={materials["[Color M09]"]}
                      position={[6.099, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_49.geometry}
                      material={materials["[Color M09]"]}
                      position={[21.599, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_50.geometry}
                      material={materials["[Color M09]"]}
                      position={[13.849, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_51.geometry}
                      material={materials["[Color M09]"]}
                      position={[-172.026, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_52.geometry}
                      material={materials["[Color M09]"]}
                      position={[-9.276, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_53.geometry}
                      material={materials["[Color M09]"]}
                      position={[-1.526, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_54.geometry}
                      material={materials["[Color M09]"]}
                      position={[-156.526, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_55.geometry}
                      material={materials["[Color M09]"]}
                      position={[-24.776, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_56.geometry}
                      material={materials["[Color M09]"]}
                      position={[-141.026, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_57.geometry}
                      material={materials["[Color M09]"]}
                      position={[-86.776, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_58.geometry}
                      material={materials["[Color M09]"]}
                      position={[-133.276, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_59.geometry}
                      material={materials["[Color M09]"]}
                      position={[-79.026, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_60.geometry}
                      material={materials["[Color M09]"]}
                      position={[-164.276, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_61.geometry}
                      material={materials["[Color M09]"]}
                      position={[-117.776, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_62.geometry}
                      material={materials["[Color M09]"]}
                      position={[-40.276, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_63.geometry}
                      material={materials["[Color M09]"]}
                      position={[-125.526, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_64.geometry}
                      material={materials["[Color M09]"]}
                      position={[-110.026, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_65.geometry}
                      material={materials["[Color M09]"]}
                      position={[-102.276, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_66.geometry}
                      material={materials["[Color M09]"]}
                      position={[-94.526, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_67.geometry}
                      material={materials["[Color M09]"]}
                      position={[-148.776, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                    <mesh
                      geometry={nodes.Geom3D_68.geometry}
                      material={materials["[Color M09]"]}
                      position={[-71.276, -0.139, -5.603]}
                      rotation={[0, -0.03, 0]}
                    />
                  </group>
                  <mesh
                    geometry={nodes.Geom3D__1.geometry}
                    material={materials["[Color M09]"]}
                    position={[220.874, Math.PI, 0]}
                    rotation={[0, 0, 0.007]}
                    scale={[1.21, 1, 1]}
                  />
                </group>
              </group>
            </group>
            <group
              position={[0.339, 76.043, 14.873]}
              rotation={[0, -0.335, -1.571]}
              scale={[0.792, 1, 1]}
            >
              <group position={[0, -0.188, -1.533]}>
                <mesh
                  geometry={nodes.Geom3D_69.geometry}
                  material={materials["[Metal_Aluminum_Anodized]1"]}
                />
                <mesh
                  geometry={nodes.Geom3D_Roof_Drip_Edge_1.geometry}
                  material={materials.Default}
                />
              </group>
            </group>
            <group
              position={[1.289, 72.053, 3.875]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Geom3D_4x10_Rafter_1.geometry}
                material={materials.Plywood_08_1K}
              />
              <mesh
                geometry={nodes.Geom3D_70.geometry}
                material={materials["Maple Solid"]}
              />
            </group>
            <group
              position={[1.289, 8.053, 3.875]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Geom3D_4x10_Rafter_2.geometry}
                material={materials.Plywood_08_1K}
              />
              <mesh
                geometry={nodes.Geom3D_71.geometry}
                material={materials["Maple Solid"]}
              />
            </group>
            <group position={[50.664, 4.553, 20.667]}>
              <mesh
                geometry={nodes.Geom3D_72.geometry}
                material={materials.Plywood_08_1K}
              />
              <mesh
                geometry={nodes.Geom3D_2x_Wall_Plate_1.geometry}
                material={materials.Plywood_08_1K}
              />
            </group>
            <group position={[50.664, 4.553, 22.167]}>
              <mesh
                geometry={nodes.Geom3D__3.geometry}
                material={materials.Plywood_08_1K}
              />
              <mesh
                geometry={nodes.Geom3D_76.geometry}
                material={materials.Plywood_08_1K}
              />
            </group>
            <group position={[56.789, 4.553, 21.584]}>
              <mesh
                geometry={nodes.Geom3D__6.geometry}
                material={materials.Plywood_08_1K}
              />
              <mesh
                geometry={nodes.Geom3D_77.geometry}
                material={materials.Plywood_08_1K}
              />
            </group>
            <group position={[1.802, 4.553, 13.533]} rotation={[0, -0.322, 0]}>
              <mesh
                geometry={nodes.Geom3D_78.geometry}
                material={materials["western-red-cedar"]}
              />
              <mesh
                geometry={nodes.Geom3D_Difference.geometry}
                material={materials.Metal_06_1K}
              />
            </group>
            <group position={[52.164, 54.303, 22.167]}>
              <mesh
                geometry={nodes.Geom3D_80.geometry}
                material={materials["western-red-cedar"]}
              />
              <mesh
                geometry={nodes.Geom3D_81.geometry}
                material={materials.Plywood_08_1K}
              />
              <mesh
                geometry={nodes.Geom3D_82.geometry}
                material={materials["Maple Solid"]}
              />
            </group>
            <group position={[52.164, 55.803, 22.167]}>
              <mesh
                geometry={nodes.Geom3D_89.geometry}
                material={materials["western-red-cedar"]}
              />
              <mesh
                geometry={nodes.Geom3D_90.geometry}
                material={materials["Maple Solid"]}
              />
            </group>
            <group position={[52.164, 23.803, 22.167]}>
              <mesh
                geometry={nodes.Geom3D_91.geometry}
                material={materials["western-red-cedar"]}
              />
              <mesh
                geometry={nodes.Geom3D_92.geometry}
                material={materials["Maple Solid"]}
              />
            </group>
            <group position={[52.164, 22.303, 22.167]}>
              <mesh
                geometry={nodes.Geom3D_93.geometry}
                material={materials["western-red-cedar"]}
              />
              <mesh
                geometry={nodes.Geom3D_94.geometry}
                material={materials["Maple Solid"]}
              />
            </group>
            <mesh
              geometry={nodes.Geom3D.geometry}
              material={materials["131_gray slate roofing texture-seamless"]}
            />
            <mesh
              geometry={nodes.Geom3D_1.geometry}
              material={materials.Metal_06_1K}
            />
            <mesh
              geometry={nodes.Geom3D_2.geometry}
              material={materials["Carpet_01_1K copy"]}
            />
            <mesh
              geometry={nodes.Geom3D_3.geometry}
              material={materials["western-red-cedar"]}
            />
            <mesh
              geometry={nodes.Geom3D_5.geometry}
              material={materials.Roofing_01_1K}
              position={[9.452, 1.374, 17.993]}
              scale={[0.93, 0.989, 0.941]}
            />
            <mesh
              geometry={nodes.Geom3D_2x6_Stud.geometry}
              material={materials.Plywood_08_1K}
              position={[50.664, 20.553, 19.167]}
            />
            <mesh
              geometry={nodes.Geom3D_2x6_Stud_1.geometry}
              material={materials.Plywood_08_1K}
              position={[50.664, 68.553, 19.167]}
            />
            <mesh
              geometry={nodes.Geom3D_2x6_Stud_2.geometry}
              material={materials.Plywood_08_1K}
              position={[50.664, 4.553, 19.167]}
            />
            <mesh
              geometry={nodes.Geom3D_2x6_Stud_3.geometry}
              material={materials.Plywood_08_1K}
              position={[50.664, 36.553, 19.167]}
            />
            <mesh
              geometry={nodes.Geom3D_2x6_Stud_4.geometry}
              material={materials.Plywood_08_1K}
              position={[50.664, 52.553, 19.167]}
            />
            <mesh
              geometry={nodes.Geom3D_73.geometry}
              material={materials["western-red-cedar"]}
              position={[16.02, 4.573, 18.039]}
              rotation={[0, -0.322, 0]}
            />
            <mesh
              geometry={nodes.Geom3D_74.geometry}
              material={materials["[Wood OSB]"]}
              position={[50.164, 0.553, 29.653]}
            />
            <mesh
              geometry={nodes.Geom3D__2.geometry}
              material={materials.Metal_06_1K}
              position={[50.664, 12.053, 22.167]}
            />
            <mesh
              geometry={nodes.Geom3D_75.geometry}
              material={materials["western-red-cedar"]}
              position={[49.237, 4.553, 29.344]}
              rotation={[0, -0.322, 0]}
            />
            <mesh
              geometry={nodes.Geom3D__4.geometry}
              material={materials.Plywood_08_1K}
              position={[50.664, 76.053, 22.167]}
            />
            <mesh
              geometry={nodes.Geom3D__5.geometry}
              material={materials.Plywood_08_1K}
              position={[49.289, 4.553, 5.875]}
            />
            <mesh
              geometry={nodes.Geom3D__7.geometry}
              material={materials.Plywood_08_1K}
              position={[50.164, 4.553, -90.743]}
            />
            <mesh
              geometry={nodes.Geom3D_79.geometry}
              material={materials["<auto>19"]}
              position={[50.227, 0.553, 30.141]}
            />
            <mesh
              geometry={nodes.Geom3D_83.geometry}
              material={materials["western-red-cedar"]}
              position={[30.263, 4.553, 23.02]}
              rotation={[0, -0.322, 0]}
            />
            <mesh
              geometry={nodes.Geom3D__8.geometry}
              material={materials.D01_Frost_White}
              position={[1.289, 4.553, 9.443]}
            />
            <mesh
              geometry={nodes.Geom3D_84.geometry}
              material={materials["western-red-cedar"]}
              position={[20.776, 4.553, 19.857]}
              rotation={[0, -0.322, 0]}
            />
            <mesh
              geometry={nodes.Geom3D_85.geometry}
              material={materials["western-red-cedar"]}
              position={[35.006, 4.553, 24.601]}
              rotation={[0, -0.322, 0]}
            />
            <mesh
              geometry={nodes.Geom3D_86.geometry}
              material={materials["western-red-cedar"]}
              position={[24.933, 4.553, 21.241]}
              rotation={[0, -0.322, 0]}
            />
            <mesh
              geometry={nodes.Geom3D_87.geometry}
              material={materials["western-red-cedar"]}
              position={[11.289, 4.553, 16.695]}
              rotation={[0, -0.322, 0]}
            />
            <mesh
              geometry={nodes.Geom3D_88.geometry}
              material={materials["western-red-cedar"]}
              position={[25.52, 4.553, 21.439]}
              rotation={[0, -0.322, 0]}
            />
            <mesh
              geometry={nodes.Geom3D_95.geometry}
              material={materials["western-red-cedar"]}
              position={[44.493, 4.553, 27.763]}
              rotation={[0, -0.322, 0]}
            />
            <mesh
              geometry={nodes.Geom3D_96.geometry}
              material={materials["western-red-cedar"]}
              position={[6.546, 4.553, 15.114]}
              rotation={[0, -0.322, 0]}
            />
            <mesh
              geometry={nodes.Geom3D__9.geometry}
              material={materials.Metal_06_1K}
              position={[50.664, 44.053, 22.167]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(staticFile("roof.glb"));
