import { z } from "zod";

// ─── Shared narration sub-schema ─────────────────────────────────────────────

/**
 * Narration config carried by every scene.
 *
 * - `script`         — the voiceover text for this scene (auto-generated by
 *                      `/api/whiteboard-voiceover` if not supplied)
 * - `audioUrl`       — Vercel Blob URL returned after TTS generation; Remotion
 *                      `<Audio>` plays this in sync with the scene sequence
 * - `audioDurationMs` — actual audio duration returned by the TTS pipeline;
 *                      when set, scene `durationInFrames` is extended to match
 */
const narrationSchema = z.object({
  audioUrl: z.string().optional(),
  audioDurationMs: z.number().optional(),
  script: z.string().optional(),
});

// ─── Shared drawing sub-schema ───────────────────────────────────────────────

/**
 * An AI-generated whiteboard drawing for a scene.
 *
 * - `prompt`   — plain-English description of what to draw, sent to the
 *                generation API (POST /api/whiteboard/drawing)
 * - `paths`    — ordered array of SVG path d-attributes returned by the API;
 *                each path = one pen stroke, animated sequentially
 * - `viewBox`  — SVG viewBox string returned by the API (default "0 0 300 300")
 */
const drawingSchema = z.object({
  prompt: z.string().optional(),
  paths: z.array(z.string()).optional(),
  viewBox: z.string().default("0 0 300 300"),
});

const titleSceneSchema = z.object({
  type: z.literal("title"),
  durationInFrames: z.number().default(120),
  eyebrow: z.string().optional(),
  headline: z.string().default("Your Headline Here"),
  subtitle: z.string().optional(),
  narration: narrationSchema.optional(),
  /** FAL AI generated illustration URL shown as a right-side panel. */
  illustrationUrl: z.string().optional(),
  drawing: drawingSchema.optional(),
});

const bulletsSceneSchema = z.object({
  type: z.literal("bullets"),
  durationInFrames: z.number().default(210),
  heading: z.string().default("Key Points"),
  bullets: z
    .array(z.string())
    .default(["Point one", "Point two", "Point three"]),
  useCheckboxes: z.boolean().default(true),
  narration: narrationSchema.optional(),
  illustrationUrl: z.string().optional(),
  drawing: drawingSchema.optional(),
});

const calloutSceneSchema = z.object({
  type: z.literal("callout"),
  durationInFrames: z.number().default(150),
  label: z.string().default("Did You Know?"),
  stat: z.string().default("80%"),
  body: z.string().default("of homeowners don't file when they should."),
  emphasis: z.string().optional(),
  narration: narrationSchema.optional(),
  illustrationUrl: z.string().optional(),
  drawing: drawingSchema.optional(),
});

const diagramSceneSchema = z.object({
  type: z.literal("diagram"),
  durationInFrames: z.number().default(240),
  heading: z.string().default("The Process"),
  steps: z
    .array(
      z.object({
        label: z.string(),
        detail: z.string().optional(),
      })
    )
    .default([
      { label: "Inspect", detail: "Free roof assessment" },
      { label: "Document", detail: "Photos + report" },
      { label: "Navigate", detail: "Insurance + repairs" },
    ]),
  narration: narrationSchema.optional(),
  illustrationUrl: z.string().optional(),
  drawing: drawingSchema.optional(),
});

const ctaSceneSchema = z.object({
  type: z.literal("cta"),
  durationInFrames: z.number().default(120),
  headline: z.string().default("Ready to get started?"),
  action: z.string().default("Call or text: 512-968-3965"),
  byline: z.string().default("Tandra Peters · Birdcreek Roofing"),
  badge: z.string().optional(),
  narration: narrationSchema.optional(),
  illustrationUrl: z.string().optional(),
  drawing: drawingSchema.optional(),
});

export const whiteboardSceneSchema = z.discriminatedUnion("type", [
  titleSceneSchema,
  bulletsSceneSchema,
  calloutSceneSchema,
  diagramSceneSchema,
  ctaSceneSchema,
]);

// ─── Top-level composition schema ─────────────────────────────────────────────

export const whiteboardVideoSchema = z.object({
  /**
   * Accent color for headings, underlines, and emphasis strokes.
   * Default Birdcreek blue.
   */
  accentColor: z.string().default("#1D4ED8"),
  /** Paper/canvas background color. */
  backgroundColor: z.string().default("#FAFAF7"),
  /** Ink color for drawn lines and text. */
  inkColor: z.string().default("#1C1C1C"),
  /** Show the animated hand/marker cursor when drawing. */
  showHand: z.boolean().default(true),
  /**
   * URL to the processed hand-marker.webm (VP9 + alpha, black bg removed).
   * Takes priority over `handSrc` when both are set.
   * Generated by: `ffmpeg -vf "colorkey=black:similarity=0.25:blend=0.08,format=yuva420p"`.
   */
  handVideoSrc: z.string().optional(),
  /**
   * URL to a real hand-holding-marker PNG (transparent background preferred).
   * When set, the HandMarker component composites this image instead of the
   * SVG fallback. Drop in your photo/render once ready.
   *
   * The image should show a hand from the lower-right with the marker tip
   * pointing left. The tip anchor is controlled by `handTipXRatio` /
   * `handTipYRatio` (both default to the typical position for this pose).
   */
  handSrc: z.string().optional(),
  /** Horizontal position of the marker tip within the hand image (0–1). Default 0.14. */
  handTipXRatio: z.number().optional(),
  /** Vertical position of the marker tip within the hand image (0–1). Default 0.78. */
  handTipYRatio: z.number().optional(),
  /**
   * ElevenLabs voice ID to use for TTS narration generation.
   * Set this to Tandra's cloned voice ID after creating it in the ElevenLabs
   * dashboard. Falls back to `ELEVENLABS_TANDRA_VOICE_ID` (then
   * `ELEVENLABS_DEFAULT_VOICE_ID`) env var on the server.
   */
  voiceId: z.string().optional(),
  /** Ordered scenes that make up the video. */
  scenes: z.array(whiteboardSceneSchema).default([]),
});

export type WhiteboardScene = z.infer<typeof whiteboardSceneSchema>;
export type WhiteboardVideoProps = z.infer<typeof whiteboardVideoSchema>;
export type TitleScene = z.infer<typeof titleSceneSchema>;
export type BulletsScene = z.infer<typeof bulletsSceneSchema>;
export type CalloutScene = z.infer<typeof calloutSceneSchema>;
export type DiagramScene = z.infer<typeof diagramSceneSchema>;
export type CtaScene = z.infer<typeof ctaSceneSchema>;
export type Narration = z.infer<typeof narrationSchema>;
export type SceneDrawing = z.infer<typeof drawingSchema>;
